house/urls.py
from django.urls import path
from . import views

# namespace
app_name = 'house'

urlpatterns = [

    # 展示文章列表并筛选 -  登录/未登录均可
    path('', views.house_filter, name='house_filter'),

    ]

myhouseproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('house.urls')),
]

house/models.py
from django.db import models

# Create your models here.


class City(models.TextChoices):
    BEIJING = 'bj', '北京'
    SHANGHAI = 'sh', '上海'
    SHENZHEN = 'sz', '深圳'
    GUANGZHOU = 'gz', '广州'
    HANGZHOU = 'hz', '杭州'


class Bedroom(models.TextChoices):
    B1 = '1', '1室1厅'
    B2 = '2', '2室1厅'
    B3 = '3', '3室1厅'
    B4 = '4', '4室2厅'


class Area(models.TextChoices):
    A1 = '1', '<50平米'
    A2 = '2', '50-70平米'
    A3 = '3', '70-90平米'
    A4 = '4', '90-140平米'
    A5 = '5', '>140平米'


class Floor(models.TextChoices):
    LOW = 'l', '低楼层'
    MIDDLE = 'm', '中楼层'
    HIGH = 'h', '高楼层'


class Direction(models.TextChoices):
    EAST = 'e', '东'
    SOUTH = 's', '南'
    WEST = 'w', '西'
    NORTH = 'n', '北'


class Community(models.Model):
    name = models.CharField(max_length=60, verbose_name='小区')
    city = models.CharField(max_length=2, choices=City.choices, verbose_name="城市")
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="发布日期")
    mod_date = models.DateTimeField(auto_now=True, verbose_name="修改日期")

    class Meta:
        verbose_name = "小区"
        verbose_name_plural = "小区"

    def __str__(self):
        return self.name


class House(models.Model):
    description = models.CharField(max_length=108, verbose_name="描述")
    community = models.ForeignKey('Community', on_delete=models.CASCADE, verbose_name="小区")
    bedroom = models.CharField(max_length=1, choices=Bedroom.choices, verbose_name="房型")
    direction = models.CharField(max_length=2, choices=Direction.choices, verbose_name="朝向")
    floor = models.CharField(max_length=1, choices=Floor.choices, verbose_name="楼层")
    area = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="面积(平方米)")
    area_class = models.CharField(max_length=1, null=True, blank=True, choices=Area.choices, verbose_name="面积")
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="价格(万元)")
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="发布日期")
    mod_date = models.DateTimeField(auto_now=True, verbose_name="修改日期")

    class Meta:
        verbose_name = "二手房"
        verbose_name_plural = "二手房"

    def __str__(self):
        return '{}.{}'.format(self.description, self.community)

    def save(self, *args, **kwargs):
        if self.area < 50:
            self.area_class = Area.A1
        elif 50 <= self.area < 70:
            self.area_class = Area.A2
        elif 70 <= self.area < 90:
            self.area_class = Area.A3
        elif 90 <= self.area < 140:
            self.area_class = Area.A4
        else:
            self.area_class = Area.A5

        super().save(*args, **kwargs)

house/views.py
from django.shortcuts import render
from .models import House
from .filters import HouseFilter
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.


# Filter houses
def house_filter(request):
    base_qs = House.objects.all().select_related('community')
    f = HouseFilter(request.GET, queryset=base_qs)
    paginator = Paginator(f.qs, 5)
    page = request.GET.get('page', 1)
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    is_paginated = True if paginator.num_pages > 1 else False
    context = {'page_obj': page_obj, 'paginator': paginator, 'is_paginated': is_paginated, 'filter': f, }

    return render(request, 'house/house_filter.html', context)

house/templates/house/base.html
<!DOCTYPE html>
{% load static %}
{% load core_tags_filters %}
<html lang="en">
  <head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Quickly get a project started with any of our examples ranging from using parts of the framework to custom components and layouts.">
	<title>大江狗房产</title>

	<link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/">
	<!-- Bootstrap core CSS -->
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

	 <style>
	 html {
	  box-sizing: border-box;
	}

	* {
	  box-sizing: inherit;
	}
	*:before, *:after {
	  box-sizing: inherit;
	}

	body {
	   overflow-x: hidden; /* Prevent scroll on narrow devices */
	  font-family: 'Inter', Arial, sans-serif;
	  color: #8A91B4;
	  background: #F6F8FF;
	}

	table th, td
	{
    color: #666;
	}

	body a
	{
	color:#666;
	}

	body a:hover
	{
	text-decoration:none;
	color:#0071BC;
	}


	body {
	  padding-top: 56px;
	}

	.navbar .navbar-toggler
	{
	border:none;
	padding:5px;
	}

	.navbar-nav .nav-item .nav-link:hover {

	color: orange !important;
	}

   .navbar-nav > li.active > a {
	font-weight:500;
	color:#666 !important;
	}

	@media (max-width: 767.98px) {

	  .offcanvas-collapse {
		position: fixed;
		top: 56px; /* Height of navbar */
		bottom: 0;
		width: 100%;
		padding-right: 1rem;
		padding-left: 1rem;
		overflow-y: auto;
		background-color: #fafafa;
		transition: -webkit-transform .3s ease-in-out;
		transition: transform .3s ease-in-out;
		transition: transform .3s ease-in-out, -webkit-transform .3s ease-in-out;
		-webkit-transform: translateX(100%);
		transform: translateX(100%);
	  }
	  .offcanvas-collapse.open {
		-webkit-transform: translateX(-1rem);
		transform: translateX(-1rem); /* Account for horizontal padding on navbar */
	  }


	}


	#myTab li
	{
	background:none;
	border:none;
	padding-left:0px;
	margin-right:15px;
	padding-right:0px;
	}


    #myTab li a,  #myTab a
	{
	border:none;
	background:none;
	padding-left:0px;
	padding-right:0px;
	}

	#myTab li a.active
	{
	color:orange;
	border-bottom:2px solid orange;
	}



	 @supports (-webkit-appearance: none) or (-moz-appearance: none) {
  input[type='checkbox'],
  input[type='radio'] {
    --active: #275EFE;
    --active-inner: #fff;
    --focus: 2px rgba(39, 94, 254, .3);
    --border: #BBC1E1;
    --border-hover: #275EFE;
    --background: #fff;
    --disabled: #F6F8FF;
    --disabled-inner: #E1E6F9;
    -webkit-appearance: none;
    -moz-appearance: none;
    height: 21px;
    outline: none;
    display: inline-block;
    vertical-align: top;
    position: relative;
    margin: 0;
    cursor: pointer;
    border: 1px solid var(--bc, var(--border));
    background: var(--b, var(--background));
    -webkit-transition: background .3s, border-color .3s, box-shadow .2s;
    transition: background .3s, border-color .3s, box-shadow .2s;
  }
  input[type='checkbox']:after,
  input[type='radio']:after {
    content: '';
    display: block;
    left: 0;
    top: 0;
    position: absolute;
    -webkit-transition: opacity var(--d-o, 0.2s), -webkit-transform var(--d-t, 0.3s) var(--d-t-e, ease);
    transition: opacity var(--d-o, 0.2s), -webkit-transform var(--d-t, 0.3s) var(--d-t-e, ease);
    transition: transform var(--d-t, 0.3s) var(--d-t-e, ease), opacity var(--d-o, 0.2s);
    transition: transform var(--d-t, 0.3s) var(--d-t-e, ease), opacity var(--d-o, 0.2s), -webkit-transform var(--d-t, 0.3s) var(--d-t-e, ease);
  }
  input[type='checkbox']:checked,
  input[type='radio']:checked {
    --b: var(--active);
    --bc: var(--active);
    --d-o: .3s;
    --d-t: .6s;
    --d-t-e: cubic-bezier(.2, .85, .32, 1.2);
  }
  input[type='checkbox']:disabled,
  input[type='radio']:disabled {
    --b: var(--disabled);
    cursor: not-allowed;
    opacity: .9;
  }
  input[type='checkbox']:disabled:checked,
  input[type='radio']:disabled:checked {
    --b: var(--disabled-inner);
    --bc: var(--border);
  }
  input[type='checkbox']:disabled + label,
  input[type='radio']:disabled + label {
    cursor: not-allowed;
  }
  input[type='checkbox']:hover:not(:checked):not(:disabled),
  input[type='radio']:hover:not(:checked):not(:disabled) {
    --bc: var(--border-hover);
  }
  input[type='checkbox']:focus,
  input[type='radio']:focus {
    box-shadow: 0 0 0 var(--focus);
  }
  input[type='checkbox']:not(.switch),
  input[type='radio']:not(.switch) {
    width: 21px;
  }
  input[type='checkbox']:not(.switch):after,
  input[type='radio']:not(.switch):after {
    opacity: var(--o, 0);
  }
  input[type='checkbox']:not(.switch):checked,
  input[type='radio']:not(.switch):checked {
    --o: 1;
  }
  input[type='checkbox'] + label,
  input[type='radio'] + label {
    font-size: 14px;
    line-height: 21px;
    display: inline-block;
    vertical-align: top;
    cursor: pointer;
    margin-left: 4px;
  }

  input[type='checkbox']:not(.switch) {
    border-radius: 7px;
  }
  input[type='checkbox']:not(.switch):after {
    width: 5px;
    height: 9px;
    border: 2px solid var(--active-inner);
    border-top: 0;
    border-left: 0;
    left: 7px;
    top: 4px;
    -webkit-transform: rotate(var(--r, 20deg));
            transform: rotate(var(--r, 20deg));
  }
  input[type='checkbox']:not(.switch):checked {
    --r: 43deg;
  }
  input[type='checkbox'].switch {
    width: 38px;
    border-radius: 11px;
  }
  input[type='checkbox'].switch:after {
    left: 2px;
    top: 2px;
    border-radius: 50%;
    width: 15px;
    height: 15px;
    background: var(--ab, var(--border));
    -webkit-transform: translateX(var(--x, 0));
            transform: translateX(var(--x, 0));
  }
  input[type='checkbox'].switch:checked {
    --ab: var(--active-inner);
    --x: 17px;
  }
  input[type='checkbox'].switch:disabled:not(:checked):after {
    opacity: .6;
  }

  input[type='radio'] {
    border-radius: 50%;
  }
  input[type='radio']:after {
    width: 19px;
    height: 19px;
    border-radius: 50%;
    background: var(--active-inner);
    opacity: 0;
    -webkit-transform: scale(var(--s, 0.7));
            transform: scale(var(--s, 0.7));
  }
  input[type='radio']:checked {
    --s: .5;
  }
}

    .tb-filter-item a
    {
    margin-left:20px;
    }

</style>



  </head>

  <body>
     <nav class="navbar navbar-expand-md fixed-top navbar-light box-shadow bg-white">
	  <div class="container">

       <a class="navbar-brand align-items-md-center" href="index.html">大江狗房产网</a>
      <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">


		<ul class="navbar-nav ml-auto">
			<li class="nav-item">
			<a class="nav-link text-uppercase" href="#">二手房</a>
		  </li>
		  <li class="nav-item ">
			<a class="nav-link text-uppercase" href="#">新房</a>
		  </li>
		  <li class="nav-item">
			<a class="nav-link text-uppercase" href="#">租房</a>
		  </li>

		  <li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle text-uppercase" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">关于我们</a>
			<div class="dropdown-menu" aria-labelledby="dropdown04">
			  <a class="dropdown-item text-muted" href="#">管理团队</a>
			  <a class="dropdown-item text-muted" href="#">联系我们</a>
			</div>
		  </li>
        </ul>

		 <a class="btn btn-outline-secondary mb-3 mb-md-0 ml-md-3" href="main.html">登录</a>

      </div>
	  </div>
    </nav>

{% block content %}

     {% endblock %}


<footer class="bd-footer bg-light">
    <div class="container pt-3 pb-2 px-3 px-md-2">
		<ul class="bd-footer-links list-unstyled text-muted list-inline pb-2">
		  <li class="list-inline-item">

		  <small>&#169; 大江狗房产网</small>
		  </li>
		  <li class="list-inline-item right"><a href="https://twitter.com/getbootstrap"><small>Privacy & Cookie</small></a></li>
		  <li class="list-inline-item right"><a href="/docs/4.5/examples/"><small>Terms & Conditions</small></a></li>
		  <li class="list-inline-item right"><a href="/docs/4.5/about/overview/"><small>ICP-9042378-6</small></a></li>
		</ul>
	</div>
</footer>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script>
$(function () {
  'use strict'

  $('[data-toggle="offcanvas"]').on('click', function () {
    $('.offcanvas-collapse').toggleClass('open')
  })
})
</script>


</html>

house/templates/house/house_filter.html
{% extends 'house/base.html' %}
{% load static %}
{% load core_tags_filters %}


{% block content %}
<div class="py-4 px-3 bg-light">
     <div class="container">

	          <!-- Nav tabs 3 -->
			 <div class="row">
				<div class="col-1 col-md-2"></div>
				<div class="col-10 col-md-8">

				<ul class="nav nav-tabs px-1 mx-0" id="myTab" role="tablist">
					<li class="nav-item">
							<a class="nav-link active" id="home-tab" data-toggle="tab" href="#tabpanel1" role="tab" aria-controls="home" aria-selected="true">二手房</a>
					</li>
				    <li class="nav-item">
							<a class="nav-link" id="profile-tab" data-toggle="tab" href="#tabpanel2" role="tab" aria-controls="profile" aria-selected="false">新房</a>
				    </li>
					<li class="nav-item">
							<a class="nav-link" id="messages-tab" data-toggle="tab" href="#tabpanel3" role="tab" aria-controls="messages" aria-selected="false">租房</a>
					</li>
				</ul>
				</div>
				<div class="col-1 col-md-8"></div>
				</div>


				<div class="tab-content">

				<div class="tab-pane fade show active" id="tabpanel1" role="tabpanel" aria-labelledby="home-tab">

					 <div class="row pt-3">
						<div class="col-1 col-md-2"></div>
						<div class="col-10 col-md-8">
					 <form role="form" method="get" action="{% url 'house:house_filter' %}">
						<div class="input-group">

							<input type="text" name="q" value="{% if filter.form.q.value %}{{ filter.form.q.value }}{% endif %}" class="form-control" id="id_q" placeholder="关键词或小区名">

							<div class="input-group-append">
									<button type="submit" class="btn btn-inline btn-sm bg-warning">
									<svg class="bi bi-search" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
									  <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
									  <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
									</svg>
									</button>
							 </div>

						</div>
					</form>

					</div>
					<div class="col-1 col-md-2"></div>
					</div>

		      </div>

			  <div class="tab-pane fade" id="tabpanel2" role="tabpanel" aria-labelledby="profile-tab">

		     </div>
			  <div class="tab-pane fade" id="tabpanel3" role="tabpanel" aria-labelledby="messages-tab">

			  </div>

			</div>
	  </div>
</div>

	 <div class="py-4 px-3 bg-white">
     <div class="container">
         <table class="mb-4" style="font-size:14px">
	   <tbody>


         {% with field=filter.form.city %}
        <!-- checkbox -->
         <tr class="mt-2">
             <td class="align-text-top" style="width:40px;"><span><b>城市</b></span></td>
             <td class="tb-filter-item">
                  <a href="?{% param_replace city='' %}">
                    <input type="checkbox"
                     {% if not request.GET.city %}
                          checked="checked"
                           {% endif %}
                     disabled />
                    <span>全部</span>
                  </a>

            {% for pk, choice in field.field.widget.choices %}
                 {% ifnotequal forloop.counter0 0 %}
                      <a href="?{% param_replace city=pk %}" class="align-items-center">
                    <input id="id_{{field.name}}_{{ forloop.counter0 }}" name="{{field.name}}"
                           type="checkbox" value="{{pk}}" class=""
                             {% ifequal field.value pk %}
                               checked="checked"
                             {% endifequal %} disabled />
                    <span>{{ choice }}</span>
                        </a>
                 {% endifnotequal %}
            {% endfor %}
            </td>
         </tr>

         {% endwith %}



         {% with field=filter.form.bedroom %}
        <!-- checkbox -->
         <tr>
             <td class="align-text-top" style="width:40px;"><span><b>{{ field.label }}</b></span></td>
             <td class="tb-filter-item">
                  <a href="?{% param_replace bedroom='' %}">
                    <input type="checkbox"
                     {% if not request.GET.bedroom %}
                          checked="checked"
                           {% endif %}
                     disabled />
                    <span>全部</span>
                  </a>

            {% for pk, choice in field.field.widget.choices %}
                 {% ifnotequal forloop.counter0 0 %}
                      <a href="?{% param_replace bedroom=pk %}" class="align-items-center">
                    <input id="id_{{field.name}}_{{ forloop.counter0 }}" name="{{field.name}}"
                           type="checkbox" value="{{pk}}" class=""
                             {% ifequal field.value pk %}
                               checked="checked"
                             {% endifequal %} disabled />
                    <span>{{ choice }}</span>
                        </a>
                 {% endifnotequal %}
            {% endfor %}
            </td>
         </tr>

         {% endwith %}

         {% with field=filter.form.area %}
        <!-- checkbox -->
         <tr class="mt-2">
             <td class="align-text-top" style="width:40px;"><span><b>{{ field.label }}</b></span></td>
             <td class="tb-filter-item">
                  <a href="?{% param_replace area='' %}">
                    <input type="checkbox"
                     {% if not request.GET.area %}
                          checked="checked"
                           {% endif %}
                     disabled />
                    <span>全部</span>
                  </a>

            {% for pk, choice in field.field.widget.choices %}
                 {% ifnotequal forloop.counter0 0 %}
                      <a href="?{% param_replace area=pk %}" class="align-items-center">
                    <input id="id_{{field.name}}_{{ forloop.counter0 }}" name="{{field.name}}"
                           type="checkbox" value="{{pk}}" class=""
                             {% ifequal field.value pk %}
                               checked="checked"
                             {% endifequal %} disabled />
                    <span>{{ choice }}</span>
                        </a>
                 {% endifnotequal %}
            {% endfor %}
            </td>
         </tr>

         {% endwith %}


         {% with field=filter.form.direction %}
        <!-- checkbox -->
        <tr class="mt-2">
             <td class="align-text-top" style="width:40px;"><span><b>{{ field.label }}</b></span></td>
             <td class="tb-filter-item">
                  <a href="?{% param_replace direction='' %}">
                    <input type="checkbox"
                     {% if not request.GET.direction %}
                          checked="checked"
                           {% endif %}
                     disabled />
                    <span>全部</span>
                  </a>

            {% for pk, choice in field.field.widget.choices %}
                 {% ifnotequal forloop.counter0 0 %}
                      <a href="?{% param_replace direction=pk %}" class="align-items-center">
                    <input id="id_{{field.name}}_{{ forloop.counter0 }}" name="{{field.name}}"
                           type="checkbox" value="{{pk}}" class=""
                             {% ifequal field.value pk %}
                               checked="checked"
                             {% endifequal %} disabled />
                    <span>{{ choice }}</span>
                        </a>
                 {% endifnotequal %}
            {% endfor %}
            </td>
         </tr>

         {% endwith %}


	 </tbody>
	 </table>

         <div class="x_title align-items-center py-1 row bg-white">
             <div class="col-6 pt-2">
                 <h6 class="align-items-center">共找到{{ filter.qs.count }}间好房<h6>
             </div>

             <div class="col-6">
                 <span class="dropdown float-right">
                    <a href="{{ request.path }}">
                     <button type="button" class="btn btn-sm btn-light py-1 my-0" aria-expanded="false">

                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-backspace-reverse" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M9.08 2H2a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h7.08a1 1 0 0 0 .76-.35L14.682 8 9.839 2.35A1 1 0 0 0 9.08 2zM2 1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h7.08a2 2 0 0 0 1.519-.698l4.843-5.651a1 1 0 0 0 0-1.302L10.6 1.7A2 2 0 0 0 9.08 1H2z"/>
                      <path fill-rule="evenodd" d="M9.854 5.146a.5.5 0 0 1 0 .708l-5 5a.5.5 0 0 1-.708-.708l5-5a.5.5 0 0 1 .708 0z"/>
                      <path fill-rule="evenodd" d="M4.146 5.146a.5.5 0 0 0 0 .708l5 5a.5.5 0 0 0 .708-.708l-5-5a.5.5 0 0 0-.708 0z"/>
                    </svg>
                         清除
                     </button>
                    </a>


                 </span>
             </div>


         </div>


         <div class="table-responsive">
             <table class="table table-striped table-hover">
                 <thead>
                 <tr>
                     <th scope="col">描述</th>
                     <th scope="col">小区</th>
                     <th scope="col">城市</th>
                     <th scope="col">房型</th>
                     <th scope="col">朝向</th>
                     <th scope="col">面积</th>
                     <th scope="col">价格(万元)</th>
                 </tr>
                 </thead>
                   <tbody>
                 {% if page_obj %}
                     {% for item in page_obj %}
                     <tr>
                         <td>{{ item.description }}</td>
                         <td>{{ item.community }}</td>
                         <td>{{ item.community.get_city_display }}</td>
                         <td>{{ item.get_bedroom_display }}</td>
                         <td>{{ item.get_direction_display }}</td>
                         <td>{{ item.area }}</td>
                         <td>{{ item.price }}</td>
                     </tr>
                     {% endfor %}
                   {% endif %}
                 </tbody>
             </table>

             {% if is_paginated %}
             <ul class="pagination">
                 {% if page_obj.has_previous %}
                 <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.previous_page_number %}">&laquo;</a></li>
                 {% else %}
                 <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                 {% endif %}

                 {% for i in paginator.page_range %}
                 {% if page_obj.number == i %}
                 <li class="page-item active"><span class="page-link"> {{ i }} <span class="sr-only">(current)</span></span></li>
                 {% else %}
                       <li class="page-item"><a class="page-link" href="?{% param_replace page=i %}">{{ i }}</a></li>
                 {% endif %}
                 {% endfor %}

                 {% if page_obj.has_next %}
                 <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.next_page_number %}">&raquo;</a></li>
                 {% else %}
                 <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                 {% endif %}
             </ul>
        {% endif %}

         </div>
	</div>
</div>
{% endblock %}